### ISSUE TITLE
import_module fails on this one import path. 

### ISSUE THREAD

**Issue by halfak** [halfak/yamlconf#4]
$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import yamlconf
> > > yamlconf.import_module("revscoring.features.revision_oriented.revision.user.is_anon")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/halfak/venv/3.5/lib/python3.5/site-packages/yamlconf/import_path.py", line 43, in import_path
> > >     module_or_attribute = getattr(module_or_attribute, attribute_name)
> > > AttributeError: module 'revscoring.features' has no attribute 'revision_oriented'

**Comment by halfak** [comment]
https://github.com/halfak/yamlconf/commit/96433e93c6972e3adef9ae6a8ef3e4a1d2c852bd

**Comment by halfak** [comment]
https://github.com/halfak/yamlconf/commit/96433e93c6972e3adef9ae6a8ef3e4a1d2c852bd

**Comment by halfak** [comment]
https://github.com/halfak/yamlconf/commit/96433e93c6972e3adef9ae6a8ef3e4a1d2c852bd

**Comment by halfak** [comment]
https://github.com/halfak/yamlconf/commit/96433e93c6972e3adef9ae6a8ef3e4a1d2c852bd
